/**
 * @file app.h
 * @brief Public interface of the application layer.
 *
 * This header exposes the small public API used by the firmware entry point
 * to initialize the application, execute its cooperative loop, and read the
 * latest telemetry snapshot generated by the app.
 *
 * The implementation behind this API depends on the selected build profile:
 *  - APP_DIAG_BUILD   : diagnostic build with UART-oriented observability
 *  - APP_FLIGHT_BUILD : flight build with apogee detection and SD logging
 *
 * ---------------------------------------------------------------------------
 * Project      : Avionics Software
 * Organization : GC_ULE (Grupo de Cohetería ULE)
 * Version      : v1.0
 * ---------------------------------------------------------------------------
 */

#pragma once
#include "app_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Initializes the application and all enabled modules.
 *
 * This function clears the global application context, initializes the OSAL
 * transports, attempts to bring up the enabled modules, creates the periodic
 * task table, and arms the cooperative scheduler.
 */
void app_init(void);

/**
 * @brief Executes one iteration of the cooperative application loop.
 *
 * The function updates the current timestamp stored in telemetry and dispatches
 * every task whose next activation time has expired.
 */
void app_loop(void);

/**
 * @brief Returns a pointer to the latest telemetry snapshot.
 *
 * @return Pointer to the internal telemetry structure owned by the app
 */
const telemetry_t* app_get_telemetry(void);

#ifdef __cplusplus
}
#endif
